#!/bin/bash

#DEST=192.168.5.6
DEST=rumkin.com

rsync -axzvP --delete --delete-during --delete-excluded \
	--exclude /.cache/ \
	--exclude /.config/google-chrome/ \
	--exclude /.dropbox/ \
	--exclude /.evolution/ \
	--exclude /.gtk-gnutella/tth_cache/ \
	--exclude /.local/share/Trash/ \
	--exclude /.macromedia/ \
	--exclude /.mozilla/firefox\*/\*/OfflineCache/ \
	--exclude /.mozilla/firefox\*/\*/Cache/ \
	--exclude /.nautilus/ \
	--exclude /.openoffice.org \
	--exclude /.opera/ \
	--exclude /.PlayOnLinux/ \
	--exclude /.pulse/ \
	--exclude /.thumbnails/ \
	--exclude /.VirtualBox/ \
	--exclude /.vlc/ \
	--exclude /.wine/ \
	--exclude /.winetrickscache/ \
	--exclude /gtk-gnutella-downloads/ \
	--exclude /Dropbox/ \
	--exclude /rumkin/ \
	--exclude /rumkin-media/ \
	--exclude /Ubuntu\ One/ \
	${HOME}/ ${USER}@${DEST}:`uname -n`/
