#!/bin/bash

INFILE="$1"
OUTFILE="$2"
SKIP_TESTS="$3"

if [ -z "$INFILE" ]; then
	INFILE="-"
fi

if [ -z "$OUTFILE" ]; then
	OUTFILE="$INFILE"
fi

# Create temp file
TEMPFILE="`mktemp`"

# Beautify
php_beautifier -d ~/bin/conf/ -l "beautify()" "$INFILE" > "$TEMPFILE"

# Lint check
if [ -z "$SKIP_TESTS" ] && ! php -l "$TEMPFILE" > /dev/null 2>&1; then
	echo "Beautified code is invalid PHP" > /dev/stderr
	echo " IN:  $INFILE" > /dev/stderr
	echo "OUT:  $TEMPFILE" > /dev/stderr
	exit 1
fi

if [ "$OUTFILE" == "-" ]; then
	cat "$TEMPFILE"
else
	# Use cat to preserve file permissions
	cat "$TEMPFILE" > "$OUTFILE"
fi

rm "$TEMPFILE"
exit 0
