#!/bin/bash

FG="1 30 1;30 31 1;31 32 1;32 33 1;33 34 1;34 35 1;35 36 1;36 37 1;37"
BG="40 41 42 43 44 45 46 47"

# Lines

for FGN in '' $FG; do
	for BGN in '' $BG; do
		COLOR=""

		if [ ! -z "$FGN" ]; then
			COLOR="${FGN}"
		fi

		if [ ! -z "$BGN" ]; then
			if [ ! -z "$COLOR" ]; then
				COLOR="${COLOR};"
			fi

			COLOR="${COLOR}${BGN}"
		fi

		COLOR="${COLOR}m"
		printf " \e[${COLOR}";

		if [ -z "$BGN" ]; then
			printf "%5s" "$COLOR"
		else
			printf "%8s" "$COLOR"
		fi

		printf "\e[m" # Reset
	done

	printf "\n"
done
