#!/usr/bin/env bash
# https://stackoverflow.com/questions/6841143/how-to-set-font-color-for-stdout-and-stderr#answer-16178979

(
    set -o pipefail
    "$@" 2>&1 >&3 | sed $'s,.*,\e[31m&\e[m,' >&2
) 3>&1

