#!/bin/bash

echo "You did run this in screen, right?"
echo "If not, Control-C out now."
read

emerge --sync
fixpackages
emerge --newuse --deep world
revdep-rebuild
emerge --depclean
perl-cleaner all
python-updater

echo ""
echo "Now you need to manually run dispatch-conf or etc-update"
