#!/usr/bin/env bash

fromDate=$(date --date="last saturday -6 days" +%s)000
toDate=$(date --date="last saturday" +%s)000
fromCurrency=GBP
toCurrency=USD

curl "https://api.ofx.com/PublicSite.ApiService/SpotRateHistory/${fromCurrency}/${toCurrency}/${fromDate}/${toDate}?DecimalPlaces=6&ReportingInterval=daily" | \
    tr "," "\n" | \
    grep "^\"Average\":[.0-9]*"
