#!/bin/bash

get-size() {
    if [[ "$1" == "4b825dc642cb6eb9a060e54bf8d69288fbee4904" ]]; then
        echo 0
    else
        git ls-tree -lrt "$1" | grep blob | awk '{print $4}' | paste -sd+ - | bc
    fi
}

REF=$1
AGAINST=$2

if [[ -z "$REF" ]]; then
    REF=HEAD
fi

if [[ -z "$AGAINST" ]]; then
    AGAINST=$(git cat-file -p "$REF" | grep ^parent | head -n 1 | awk '{print $2}')
fi

if [[ -z "$AGAINST" ]]; then
    AGAINST=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

echo -n "$REF "
echo "$(git cat-file -s "$REF") + $(get-size "$REF") - $(get-size "$AGAINST")" | bc
