#!/bin/bash

# Handbrake PPA
sudo add-apt-repository ppa:stebbins/handbrake-releases
#sudo add-apt-repository ppa:stebbins/handbrake-snapshots

# VideoLAN repository for libdvdcss (Medibuntu is dead)
wget -qO - ftp://ftp.videolan.org/pub/debian/videolan-apt.asc | sudo apt-key add -
echo "deb ftp://ftp.videolan.org/pub/debian/stable ./" | sudo tee /etc/apt/sources.list.d/libdvdcss.list
sudo apt-get update

# Update packages
sudo apt-get update && sudo apt-get upgrade -y

# Install DVD libraries and handbrake
sudo apt-get install -y libdvdread4
# installs libdvdcss2
sudo /usr/share/doc/libdvdread4/install-css.sh
sudo apt-get install -y handbrake-gtk
