#!/bin/bash

reset_proxy() {
    echo "Removing proxy from Gnome network settings"
    gsettings set org.gnome.system.proxy mode 'none'
}

case $1 in
    mouse-down)
        xte "mousedown 1"
        ;;

    play-next)
        rhythmbox-client --next
        ;;

    play-pause)
        rhythmbox-client --play-pause
        ;;

    play-previous)
        rhythmbox-client --previous
        ;;

    ssh-proxy)
        echo "Configuring Gnome network settings"
        gsettings set org.gnome.system.proxy.socks host 'localhost'
        gsettings set org.gnome.system.proxy.socks port 9892
        gsettings set org.gnome.system.proxy mode 'manual'
        trap reset_proxy SIGINT SIGTERM
        echo "Starting SSH tunnel"
        ssh -ND 9892 rumkin.com
        ;;

    window-move-left)
        xdotool windowmove --relative $(xdotool getwindowfocus) -9999 y
        ;;

    window-move-right)
        xdotool windowmove --relative $(xdotool getwindowfocus) 9999 y
        ;;

    *)
        cat <<'EOF'
Syntax:
    macro <command>

Commands:
    mouse-down         Simulate holding down the left mouse button
    play-next          Move to next song in Rhythmbox
    play-pause         Toggle the play/pause of Rhythmbox
    play-previous      Move to previous song in Rhythmbox
    ssh-proxy          Make and use a SOCKS proxy over ssh to rumkin.com
    window-move-left   Move current window to left edge of screen
    window-move-right  Move current window to right edge of screen
EOF
esac
