#!/bin/bash

case $1 in
    mouse-down)
		xte "mousedown 1"
		;;

    play-next)
	    rhythmbox-client --next
		;;

    play-pause)
		rhythmbox-client --play-pause
		;;

    play-previous)
	    rhythmbox-client --previous
		;;

    window-move-left)
	    xdotool windowmove --relative $(xdotool getwindowfocus) -9999 y
		;;

	window-move-right)
		xdotool windowmove --relative $(xdotool getwindowfocus) 9999 y
		;;

	*)
		cat <<'EOF'
Syntax:
    macro <command>

Commands:
    mouse-down         Simulate holding down the left mouse button
	play-next          Move to next song in Rhythmbox
    play-pause         Toggle the play/pause of Rhythmbox
	play-previous      Move to previous song in Rhythmbox
    window-move-left   Move current window to left edge of screen
	window-move-right  Move current window to right edge of screen
EOF
esac
