#!/usr/bin/env bash
# Yes, I love Minecraft.

cd ~/Minecraft

if [[ ! -e ~/.minecraft ]]; then
    ln -s "$PWD/minecraft" ~/.minecraft
fi

# Cert errors?
# sudo update-ca-certificates -f

minecraft-launcher
