#!/usr/bin/env bash

cd "${0/*}"
lockfile=mouse-repeat-click.lock

if [[ -f "$lockfile" ]]; then
    rm "$lockfile"
else
    touch "$lockfile"

    while [[ -f "$lockfile" ]]; do
        xte "mouseclick 1"
        sleep 0.35
    done
fi
