#!/usr/bin/env bash

if [[ ! -f "$1".par2 ]]; then
    echo "Failure: par2 does not exist: $1"
    echo "Ensure you are using the original filename, not the .par2 files"
    exit 1
fi

for fn in "$1".par2; do
    if [[ ! -s "$fn" ]]; then
        echo "Zero-byte file: $fn"
        exit 1
    fi
done

wholeOutput=$(par2 verify "$1" | tr "\r" "\n")

if [[ $? -ne 0 ]]; then
    echo "par2 verification failed"
    echo "FAILURE: $1"
    exit 1
fi

echo "$wholeOutput" | grep -q "^Target: \"${1##*/}\" - "

if [[ $? -ne 0 ]]; then
    echo "par2 files verified the wrong file: $(echo "$wholeOutput" | grep "^Target: " | cut -b 9-)"
    echo "FAILURE: $1"
    exit 1
fi

magicLines=$(echo "$wholeOutput" | while read -r line; do if [[ -z "$line" ]]; then break; fi; echo "$line"; done | grep "^Load" | sed 's/.*\r//')
desired=0

while read -r line; do
    if [[ "$line" =~ "Loading \""* ]]; then
        desired=$(echo "$line" | sed 's/.*+\([0-9]\+\)\.par2\"\.$/\1/')
        if [[ "$desired" == "$line" ]]; then
            desired=0
        fi
        while [[ "$desired" == "0"* ]]; do
            desired=${desired#0}
        done
    elif [[ "$line" =~ "Loaded"* ]]; then
        read -r a packets b c including blocks e < <( echo "$line" )
        if [[ "$including" == "including" ]]; then
            if [[ "$packets" != "$blocks" ]] || [[ "$packets" != "$desired" ]]; then
                echo "Mismatch - want $desired: $line"
                echo "FAILURE: $1"
                exit 1
            fi
        fi
    fi
done < <(echo "$magicLines")

