#!/usr/bin/env bash

randomString() {
    local charSet len

    charSet=

    if [[ "$1" == -* ]]; then
        case "$1" in
        --base64)
            charSet+=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/
            ;;

        --help)
            echo "random-string LENGTH [CHARSET]"
            echo ""
            echo "By default it uses a-z, A-Z and numbers."
            echo ""
            echo "Different sets can be created by using these flags.  You can use multiple"
            echo "flags together."
            echo ""
            echo "--base64 --lower --num --upper"
            echo ""
            echo "The default is the same as using --lower --num --upper"

            return 0
            ;;

        --hex)
            charSet+=0123456789abcdef
            ;;

        --lower)
            charSet+=abcdefghijklmnopqrstuvwxyz
            ;;

        --num)
            charSet+=0123456789
            ;;

        --upper)
            charSet+=ABCDEFGHIJKLMNOPQRSTUVWXYZ
            ;;
        esac

        shift
    fi

    len=${1:-10}
    charSet=${charSet:-abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789}

    if [[ ! -z "${2-}" ]]; then
        charSet=$2
    fi

    for (( ; len > 0; len -- )); do
        echo -n "${charSet:$RANDOM % ${#charSet}:1}"
    done

    echo ""
}

if [[ "$0" == "$BASH_SOURCE" ]] || ! [[ -n "$BASH_SOURCE" ]]; then
    randomString "$@"
fi
