#!/usr/bin/env bash

randomString() {
    local charSet len

    charSet=

    if [[ "$1" == -* ]]; then
        case "$1" in
        --base64)
            charSet+=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/
            ;;

        --lower)
            charSet+=abcdefghijklmnopqrstuvwxyz
            ;;

        --num)
            charSet+=0123456789
            ;;

        --upper)
            charSet+=ABCDEFGHIJKLMNOPQRSTUVWXYZ
            ;;
        esac

        shift
    fi

    len=${1:-10}
    charSet=${charset:-abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789}

    if [[ ! -z "${2-}" ]]; then
        charSet=$2
    fi

    for (( ; len > 0; len -- )); do
        echo -n "${charSet:$RANDOM % ${#charSet}:1}"
    done

    echo ""
}

if [[ "$0" == "$BASH_SOURCE" ]] || ! [[ -n "$BASH_SOURCE" ]]; then
    randomString "$@"
fi
