#!/bin/bash

BASH_FILE=~/.bashrc
grep "/bin/conf/bashrc" "${BASH_FILE}" > /dev/null 2>&1
if [ $? -ne 0 ]; then
	echo ". ~$USER/bin/conf/bashrc" >> "${BASH_FILE}"
fi

rm -f ~/.vimrc
ln -s bin/conf/vimrc ~/.vimrc

rm -rf ~/.vim
ln -s bin/conf/vim ~/.vim

rm -rf ~/.putty
ln -s bin/conf/putty ~/.putty

if [ ! -d ~/.ssh ]; then
	mkdir ~/.ssh
	chmod 700 ~/.ssh
fi
ln -s bin/ssh/authorized_keys ~/.ssh/authorized_keys
