#!/bin/bash

cd "`dirname "$0"`"

BASH_FILE=~/.bashrc
grep ". '`pwd`/conf/bashrc'" "${BASH_FILE}" > /dev/null 2>&1

if [ $? -ne 0 ]; then
	echo ". '`pwd`/conf/bashrc'" >> "${BASH_FILE}"
fi

for F in fonts npmrc putty vim vimrc; do
	rm -rf ~/.$F
	ln -s "`pwd`/conf/$F" ~/.$F
done

if [ ! -d ~/.ssh ]; then
	mkdir ~/.ssh
	chmod 700 ~/.ssh
fi
rm -rf ~/.ssh/authorized_keys
cat ssh/*.pub > ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
for F in config storage; do
	if [ -f "$HOME/.ssh/$F" ]; then
		mv "$HOME/.ssh/$F" "$HOME/.ssh/${F}.old";
	fi
	cp "ssh/$F" "$HOME/.ssh/$F"
	chmod 600 "$HOME/.ssh/$F"
done
