#!/bin/bash

cd "`dirname "$0"`"

BASH_FILE=~/.bashrc
grep "/bin/conf/bashrc" "${BASH_FILE}" > /dev/null 2>&1

if [ $? -ne 0 ]; then
	echo ". ~$USER/bin/conf/bashrc" >> "${BASH_FILE}"
fi

rm -f ~/.vimrc
ln -s "`pwd`/conf/vimrc" ~/.vimrc

rm -rf ~/.vim
ln -s "`pwd`/conf/vim" ~/.vim

rm -rf ~/.putty
ln -s "`pwd`/conf/putty" ~/.putty

rm -rf ~/.fonts
ln -s "`pwd`/conf/fonts" ~/.fonts

if [ ! -d ~/.ssh ]; then
	mkdir ~/.ssh
	chmod 700 ~/.ssh
fi
rm -rf ~/.ssh/authorized_keys
cat ssh/*.pub > ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
if [ -f ~/.ssh/config ]; then
	mv ~/.ssh/config ~/.ssh/config.old;
fi
cp ssh/config ~/.ssh/config
chmod 600 ~/.ssh/config
