#!/bin/bash
#
# Simple script that outputs the arguments passed in

test-arguments() {
    local I

    echo "\$#: $#"
    I=1

    while [[ $# -gt 0 ]]; do
        printf "\$%s: %q\n" $I "$1"
        I=$(($I + 1))
        shift
    done
}

if [[ "$0" == "$BASH_SOURCE" ]] || ! [[ -n "$BASH_SOURCE" ]]; then
    test-arguments "$@"
fi
