#!/bin/bash

# dpkg:  Finish last upgrade in case of crashes or problems
# Update list of packages, upgrade packages, check to see if we can upgrade
# to a new distribution version, then autoclean outdated packages
dpkg --configure -a &&
	aptitude -y update &&
	aptitude -y safe-upgrade &&
	aptitude -y dist-upgrade &&
	aptitude -y autoclean
