#!/bin/sh

COMMAND="$1"
ARGS="${1+"$@"}"
FILENAME=""

case "$COMMAND" in
	git)
		FILENAME=".git"
		;;
	grunt)
		FILENAME="Gruntfile.*"
		;;
	make)
		FILENAME="Makefile"
		;;
	npm)
		FILENAME="package.json"
		;;
esac

if [ -z "$FILENAME" ]; then
	# Check if the command is not in the path
	if ! test_for_program "$COMMAND"; then
		FILENAME="$COMMAND"
	fi
fi

if [ -z "$FILENAME" ]; then
	echo "I can't detect when to run \"$COMMAND\""
	exit 1
fi

while [ ! -f $FILENAME ] && [ ! -d $FILENAME ]; do
	if [ "$PWD" = "/" ]; then
		echo "Did not detect \"$FILENAME\" in any parent directory"
		exit 2
	fi

	cd ..
done

$ARGS
