#!/bin/bash

echo ""
echo ""
echo "You need to run vinagre manually when this works"
echo ""
echo ""

ssh -t -L 5900:localhost:5900 fidian@rumkin.com \
	ssh -t -L 5900:localhost:5900 cp@cinnamon \
	DISPLAY=:0 sudo /usr/lib/vino/vino-server
