" Turn on syntax highlighting
syntax on

" Set some colors
highlight Search term=underline cterm=underline ctermfg=green ctermbg=darkblue gui=NONE guifg=white guibg=yellow
highlight comment cterm=NONE ctermfg=darkgray
highlight visual cterm=bold ctermfg=black ctermbg=gray
highlight StatusLine cterm=NONE ctermfg=yellow ctermbg=blue
highlight String ctermfg=red

" Set tab and indent preferences
set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 smartindent autoindent

" Searching options
set incsearch ignorecase smartcase hlsearch

" Show matching brackets for a short time
set showmatch matchtime=2
set laststatus=2

" Allow backspace for everything
set backspace=indent,eol,start

" Clear the last search when opening a file
nohlsearch

" Unhighlight your search automatically when editing
" Alternately, the following map will clear your search
" map \ :noh<cr> 
nnoremap a :noh<CR>a
nnoremap A :noh<CR>A
nnoremap i :noh<CR>i
nnoremap I :noh<CR>I
nnoremap o :noh<CR>o
nnoremap O :noh<CR>O

" Allow F1 to exit edit mode.  Can bring up help, but can also remove help
inoremap <F1> <Esc>
noremap <F1> :call MapF1()<CR>

function! MapF1()
	if &buftype == "help"
		exec 'quit'
	else
		exec 'help'
	endif
endfunction

" Report after N lines changed; default is two
set report=2

" Start up on the last line we were editing
if has("autocmd")
	autocmd BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal g`\"" | endif
endif

" Have search results appear in the middle of the screen
nmap n nzzzv
nmap N Nzzzv
nmap * *zzzv
nmap # #zzzv
nmap g* g*zzzv
nmap g# g#zzzv
