#!/bin/bash

for D in */; do (
    echo ""
    echo ""
    echo ""
    echo "#"
    echo "# $D"
    echo "#"
    echo ""
	cd $D

    if [ -f Makefile ]; then
        make
        find . -maxdepth 1 -type f -perm /u+x -exec strip --strip-unneeded \{\} \;
    fi

    find . -maxdepth 1 -type f -perm /u+x -exec cp \{\} ../.. \;

    if [ -f Makefile ]; then
        make clean
    fi
); done
