#!/bin/bash

for D in */; do (
    echo ""
    echo ""
    echo ""
    echo "#"
    echo "# $D"
    echo "#"
    echo ""
	cd $D

    if [[ -f Makefile.PL ]]; then
        perl Makefile.PL
    fi

    if [[ -f Makefile ]]; then
        make

        if [[ -f "$D" ]]; then
            strip --strip-unneeded "$D"
        fi
    fi

    for F in blib/script .; do
        if [[ -f "$F/$D" ]]; then
            cp "$F/$D" ../..
        fi
    done

    if [ -f Makefile ]; then
        make clean
    fi
); done
