# Makefile automatically generated by bomrelease version 3.9 (2013/12/27 14:31:19)
#
# timeout version 5.01 (2014-12-15)

PROGRAM = timeout
SOURCE  = stderr.c errhelp.c timeout.c
OBJECT  = stderr.o errhelp.o timeout.o
DEBRIS  = a.out core *~
OFLAGS  = -g
WFLAGS  = # -Wall -Wmissing-prototypes -Wstrict-prototypes -std=c89 -pedantic
UFLAGS  = # Set on command line only
IFLAGS  = # -I directory options
DFLAGS  = # -D define options
CFLAGS  = ${OFLAGS} ${UFLAGS} ${WFLAGS} ${IFLAGS} ${DFLAGS}

all: ${PROGRAM}

${PROGRAM}: ${OBJECT}
	${CC} -o $@ ${CFLAGS} ${OBJECT} ${LDFLAGS} ${LDLIBES}

clean:
	rm -f ${OBJECT} ${DEBRIS}

realclean: clean
	rm -f ${PROGRAM} ${SCRIPT}

depend: ${SOURCE}
	mkdep --makefile=timeout.mk ${SOURCE}

# DO NOT DELETE THIS LINE or the blank line after it -- make depend uses them.

errhelp.o: errhelp.c
errhelp.o: stderr.h
stderr.o: stderr.c
stderr.o: stderr.h
timeout.o: posixver.h
timeout.o: stderr.h
timeout.o: timeout.c
